#!/usr/bin/env bash
lorean.py --stranded --short_reads IlluminacDNA.fastq --long_reads all.subset.28.uniq.fastq --pasa_db JR2_keep --working_dir MGS_Br --threads 8 --max_intron_length 1000 --proteins fungalProteins.fasta --species JR2 VDAG_Jr2_v4.0.NCBIorder.fasta.masked
lorean.py --stranded --fungus --short_reads IlluminacDNA.fastq --long_reads all.subset.28.uniq.fastq --pasa_db JR2_keep --working_dir MGS_Fu --threads 8 --max_intron_length 1000 --proteins fungalProteins.fasta  --species fusarium  VDAG_Jr2_v4.0.NCBIorder.fasta.masked
lorean.py --stranded --fungus --short_reads IlluminacDNA.fastq --long_reads all.subset.28.uniq.fastq --pasa_db JR2_keep --working_dir MGS_Br_Fu --threads 8 --max_intron_length 1000 --proteins fungalProteins.fasta --species JR2 VDAG_Jr2_v4.0.NCBIorder.fasta.masked
lorean.py --stranded --short_reads IlluminacDNA.fastq --long_reads all.subset.28.uniq.fastq --pasa_db JR2_keep --working_dir MGS --threads 8 --max_intron_length 1000 --proteins fungalProteins.fasta  --species fusarium  VDAG_Jr2_v4.0.NCBIorder.fasta.masked
#
lorean.py --fungus --short_reads IlluminacDNA.fastq --long_reads NanoporecDNA.fastq --pasa_db JR2_keep --working_dir MGnS_Fu --threads 8 --max_intron_length 1000 --proteins fungalProteins.fasta  --species fusarium  VDAG_Jr2_v4.0.NCBIorder.fasta.masked
lorean.py --fungus --short_reads IlluminacDNA.fastq --long_reads NanoporecDNA.fastq --pasa_db JR2_keep --working_dir MGnS_Br_Fu --threads 8 --max_intron_length 1000 --proteins fungalProteins.fasta --species JR2 VDAG_Jr2_v4.0.NCBIorder.fasta.masked
lorean.py --short_reads IlluminacDNA.fastq --long_reads NanoporecDNA.fastq --pasa_db JR2_keep --working_dir MGnS --threads 8 --max_intron_length 1000 --proteins fungalProteins.fasta  --species fusarium  VDAG_Jr2_v4.0.NCBIorder.fasta.masked
lorean.py --short_reads IlluminacDNA.fastq --long_reads NanoporecDNA.fastq --pasa_db JR2_keep --working_dir MGnS_Br --threads 8 --max_intron_length 1000 --proteins fungalProteins.fasta --species JR2 VDAG_Jr2_v4.0.NCBIorder.fasta.masked
#
lorean.py --stranded --short_reads IlluminacDNA.fastq --long_reads all.subset.28.uniq.fastq --pasa_db JR2_keep --working_dir pMGS_Br --threads 8 --max_intron_length 1000 --proteins fungalProteins.fasta --species JR2 VDAG_Jr2_v4.0.NCBIorder.fasta.masked.TElonger400
lorean.py --stranded --fungus --short_reads IlluminacDNA.fastq --long_reads all.subset.28.uniq.fastq --pasa_db JR2_keep --working_dir pMGS_Fu --threads 8 --max_intron_length 1000 --proteins fungalProteins.fasta  --species fusarium  VDAG_Jr2_v4.0.NCBIorder.fasta.masked.TElonger400
lorean.py --stranded --fungus --short_reads IlluminacDNA.fastq --long_reads all.subset.28.uniq.fastq --pasa_db JR2_keep --working_dir pMGS_Br_Fu --threads 8 --max_intron_length 1000 --proteins fungalProteins.fasta --species JR2 VDAG_Jr2_v4.0.NCBIorder.fasta.masked.TElonger400
lorean.py --stranded --short_reads IlluminacDNA.fastq --long_reads all.subset.28.uniq.fastq --pasa_db JR2_keep --working_dir pMGS --threads 8 --max_intron_length 1000 --proteins fungalProteins.fasta  --species fusarium  VDAG_Jr2_v4.0.NCBIorder.fasta.masked.TElonger400
#
lorean.py --fungus --short_reads IlluminacDNA.fastq --long_reads NanoporecDNA.fastq --pasa_db JR2_keep --working_dir pMGnS_Fu --threads 8 --max_intron_length 1000 --proteins fungalProteins.fasta  --species fusarium  VDAG_Jr2_v4.0.NCBIorder.fasta.masked.TElonger400
lorean.py --fungus --short_reads IlluminacDNA.fastq --long_reads NanoporecDNA.fastq --pasa_db JR2_keep --working_dir pMGnS_Br_Fu --threads 8 --max_intron_length 1000 --proteins fungalProteins.fasta --species JR2 VDAG_Jr2_v4.0.NCBIorder.fasta.masked.TElonger400
lorean.py --short_reads IlluminacDNA.fastq --long_reads NanoporecDNA.fastq --pasa_db JR2_keep --working_dir pMGnS --threads 8 --max_intron_length 1000 --proteins fungalProteins.fasta  --species fusarium  VDAG_Jr2_v4.0.NCBIorder.fasta.masked.TElonger400
lorean.py --short_reads IlluminacDNA.fastq --long_reads NanoporecDNA.fastq --pasa_db JR2_keep --working_dir pMGnS_Br --threads 8 --max_intron_length 1000 --proteins fungalProteins.fasta --species JR2 VDAG_Jr2_v4.0.NCBIorder.fasta.masked.TElonger400
#
lorean.py --stranded --short_reads IlluminacDNA.fastq --long_reads all.subset.28.uniq.fastq --pasa_db JR2_keep --working_dir FGS_Br --threads 8 --max_intron_length 1000 --proteins fungalProteins.fasta --species JR2 VDAG_Jr2_v4.0.NCBIorder.fasta
lorean.py --stranded --fungus --short_reads IlluminacDNA.fastq --long_reads all.subset.28.uniq.fastq --pasa_db JR2_keep --working_dir FGS_Fu --threads 8 --max_intron_length 1000 --proteins fungalProteins.fasta  --species fusarium  VDAG_Jr2_v4.0.NCBIorder.fasta
lorean.py --stranded --fungus --short_reads IlluminacDNA.fastq --long_reads all.subset.28.uniq.fastq --prefix_gene VDAG_JR2 --pasa_db JR2_keep --working_dir FGS_Br_Fu --threads 8 --max_intron_length 1000 --proteins fungalProteins.fasta --species JR2 VDAG_Jr2_v4.0.NCBIorder.fasta
lorean.py --stranded --short_reads IlluminacDNA.fastq --long_reads all.subset.28.uniq.fastq  --prefix_gene VDAG_JR2 --pasa_db JR2_keep --working_dir FGS --threads 8 --max_intron_length 1000 --proteins fungalProteins.fasta  --species fusarium  VDAG_Jr2_v4.0.NCBIorder.fasta
## I runned LoReAn from docker
lorean.py --fungus --short_reads IlluminacDNA.fastq --long_reads NanoporecDNA.fastq  --prefix_gene VDAG_JR2 --pasa_db JR2_keep --working_dir FGnS_Fu --threads 8 --max_intron_length 1000 --proteins fungalProteins.fasta  --species fusarium VDAG_Jr2_v4.0.NCBIorder.fasta
lorean.py --fungus --short_reads IlluminacDNA.fastq --long_reads NanoporecDNA.fastq --prefix_gene VDAG_JR2 --pasa_db JR2_keep --working_dir FGnS_Br_Fu --threads 8 --max_intron_length 1000 --proteins fungalProteins.fasta --species JR2 VDAG_Jr2_v4.0.NCBIorder.fasta
lorean.py --short_reads IlluminacDNA.fastq --long_reads NanoporecDNA.fastq --prefix_gene VDAG_JR2 --pasa_db JR2_keep --working_dir FGnS --threads 8 --max_intron_length 1000 --proteins fungalProteins.fasta --species fusarium VDAG_Jr2_v4.0.NCBIorder.fasta
lorean.py --short_reads IlluminacDNA.fastq --long_reads NanoporecDNA.fastq --prefix_gene VDAG_JR2 --pasa_db JR2_keep --working_dir FGnS_Br --threads 8 --max_intron_length 1000 --proteins fungalProteins.fasta --species JR2 VDAG_Jr2_v4.0.NCBIorder.fasta
